# Business Context OS Configuration
# Edit this file to customize your business research

# ============================================
# Target Company
# ============================================
company:
  name: "Anthropic"
  website: "https://anthropic.com"
  industry: "Artificial Intelligence"

# ============================================
# Research Goals
# ============================================
goals:
  # Primary research objective
  primary: "Identify growth opportunities in enterprise segment"
  
  # Secondary objectives
  secondary:
    - "Analyze competitive positioning vs Square and Adyen"
    - "Develop sales strategy for Fortune 500 companies"
    - "Identify potential strategic partnerships"

# ============================================
# Analysis Scope
# ============================================
scope:
  # Phase 1 depth: basic | standard | comprehensive
  phase1_depth: "comprehensive"
  
  # Strategic frameworks to apply in Phase 2
  phase2_frameworks:
    - "SWOT"
    - "Porter's Five Forces"
    - "Business Model Canvas"
    - "Value Chain Analysis"
    - "Blue Ocean Strategy"
    - "PESTEL"
    - "BCG Matrix"

# ============================================
# Competitive Analysis
# ============================================
competitors:
  - "Square"
  - "Adyen"
  - "PayPal"
  - "Braintree"

# ============================================
# Sales Intelligence (Optional)
# ============================================
target_prospects:
  - company: "Walmart"
    goal: "Understand payment infrastructure needs and pain points"
  - company: "Amazon"
    goal: "Identify partnership opportunities in logistics payments"

# ============================================
# Performance Targets (Optional)
# ============================================
performance_targets:
  revenue_growth: "40% YoY"
  market_share: "Top 3 in enterprise segment"
  customer_acquisition: "500 enterprise clients in 18 months"
  customer_retention: "95%+ annual retention rate"

# ============================================
# Data Sources
# API keys should be in .env file
# ============================================
data_sources:
  firecrawl:
    enabled: true         # Deep website scraping
    use_mcp: true         # Use MCP server (recommended)
    fallback_enabled: true  # Fallback to direct API if MCP fails

  exa:
    enabled: true         # Semantic search
    use_mcp: true         # Use MCP server (recommended)
    use_deep_researcher: true  # Use 45s AI researcher for complex queries
    fallback_enabled: true  # Fallback to direct API if MCP fails

  perplexity:
    enabled: true         # Fact verification and web search
    use_for_verification: true  # Use for fact-checking

  twitter: false        # Social signals (not yet implemented)
  crunchbase: false     # Company data (not yet implemented)
  sec_filings: false    # Public company data (not yet implemented)
  news_apis: false      # Recent news (not yet implemented)

# ============================================
# Multi-Source Verification
# ============================================
verification:
  # Enable multi-source verification (Truth Engine)
  multi_source_enabled: true

  # Minimum confidence threshold (0.0-1.0) to accept facts
  # PERMISSIVE MODE for Phase 1 (user-editable): 0.2 = accept most data with sources
  # 0.5 = moderate confidence, 0.7 = high confidence, 0.9 = very high
  min_confidence: 0.2

  # Require all facts to have source citations
  require_citation: true

  # Flag conflicts between sources for manual review
  flag_conflicts: true

  # Maximum age of sources in days (prefer recent data)
  max_source_age_days: 90

  # Minimum number of sources to verify a fact
  # Set to 1 for single-source, 2+ for cross-reference
  min_sources_required: 1

  # Cross-reference strategy: "any", "majority", "all"
  # - any: Accept if any source confirms
  # - majority: Accept if majority of sources confirm
  # - all: Accept only if all sources confirm
  cross_reference_strategy: "majority"

# ============================================
# Output Preferences
# ============================================
output:
  # Output formats: pdf, docx, json, pptx
  formats: ["pdf", "docx", "pptx", "json"]
  
  # Detail level: executive | detailed | comprehensive
  detail_level: "executive"
  
  # Include charts and visualizations
  include_visualizations: true
  
  # Generate PowerPoint presentation
  generate_presentation: true
  
  # Include appendix with raw data
  include_appendix: false

# ============================================
# Advanced Options (Optional)
# ============================================
advanced:
  # Max research steps (safety limit)
  max_steps: 50
  
  # Max steps per task
  max_steps_per_task: 10
  
  # Enable debug logging
  debug: false
  
  # Cache results for faster re-runs
  enable_cache: true
